# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14c9192a6fd0e1b4de876933e04c1e79faed61e3f0fba673386a132a4e1e06f9ce832921b7aee2d9d9d6a3ce54a6577b691d967c80df90aa6b125b3ca9c75c1c

test:
  secret_key_base: ea91af4d269a3ef626c373b779d05d22a0baa657416627c74dfe5607052f922815dddc26775672065d8897be79f415b752adf2ab4ddd823fdd202de7030be89d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
